{% set name = "icontract" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/icontract-{{ version }}.tar.gz
  sha256: 2e8196754743bd1a3659d66da2ddf1dc0950d01e535c2933bd997b02c6412a03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - asttokens >=2,<3
    - python >={{ python_min }}
    - typing_extensions
    - contextvars

test:
  imports:
    - icontract
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Parquery/icontract
  summary: Provide design-by-contract with informative violation messages.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kklein
