{% set name = "icontract" %}
{% set version = "2.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icontract-{{ version }}.tar.gz
  sha256: 2faea34400274f1e0f6b8595339ea53d07e19eec58cc440fa31de5cbee3e02b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens >=2,<3
    - python >=3.6
    - typing_extensions

test:
  imports:
    - icontract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Parquery/icontract
  summary: Provide design-by-contract with informative violation messages.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kklein
