{% set name = "icontract" %}
{% set version = "2.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/icontract-{{ version }}.tar.gz
  sha256: 281ec16f1d09bbcca7a4227e82cd10b4d5fb291f638df77c29b7acf493dd3178

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - asttokens >=2,<3
    - python >={{ python_min }}
    - typing_extensions
    - contextvars

test:
  imports:
    - icontract
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Parquery/icontract
  summary: Provide design-by-contract with informative violation messages.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kklein
